- name: Setup Julia environment
  # You may pin to the exact commit or the version.
  # uses: julia-actions/setup-julia@ee66464cb7897ffcc5322800f4b18d449794af30
  uses: julia-actions/setup-julia@v1.6.1
  with:
    # The Julia version to download (if necessary) and use. Example: 1.0.4
    version: # optional, default is 1
    # Architecture of the Julia binaries. Defaults to x64.
    arch: # optional, default is x64
    # Display InteractiveUtils.versioninfo() after installing
    show-versioninfo: # optional, default is false
